Add sorting capability back to filtering tab
jmarsh24/tangodb pull request #17
Opened 2021-04-07 12:50 UTC by jmarsh24

Sorting was removed because it didn't function via Ajax. I have added back the functionality and refactored the stimulus controller. The sorting capability and hd filters stack with the current filters.

2021-04-08 05:50 UTC, thomasstephane requested changes
Overall, first thing that comes to mind: Where are the tests? Let's enter the bit of writing tests for the things you change from now on, to stop accumulating testing dept. Write a system spec that plays with these filters.

2021-04-08 05:50 UTC, thomasstephane commented on app/assets/stylesheets/shared/header.scss
> +      color: #c2c2c2;
I recommend making a dictionary of colors with variables, that you reuse throughout the app, one accent color and a few nuance shades. Put them in a /shared/colors.scss file, load it first and then use the variables here.

2021-04-08 05:50 UTC, thomasstephane commented on app/assets/stylesheets/videos/index/filters.scss
> +  height: 315px;
What does this represent? is that a random arbitrary number? a calculation of sorts?

2021-04-08 05:50 UTC, thomasstephane commented on app/assets/stylesheets/videos/index/filters.scss
> +  margin: 0 .5rem .5rem .5rem;
do you know what rem is? why not px? you have a mix of both throughout your css, this feels like randomly used.

2021-04-08 05:50 UTC, thomasstephane commented on app/assets/stylesheets/videos/index/filters.scss
> +  border-bottom: 1px solid rgba(0, 0, 0, 0.1);
same comment as before on the colors

2021-04-08 05:50 UTC, thomasstephane commented on app/assets/stylesheets/videos/index/filters.scss
>  .videos-sortable-btn {
Why the "btn" ? it's a button? call it a button, characters are cheap but help carry meaning better.

2021-04-08 05:50 UTC, thomasstephane commented on app/controllers/videos_controller.rb
> +    @videos_paginated = @videos_paginated.shuffle if filtering_params.blank? && sorting_params.blank?
this whole index action is far too busy. What does it do?
Extract that logic in an few other appropriately named methods or an object

2021-04-08 05:50 UTC, thomasstephane commented on app/helpers/application_helper.rb
> +    link_to "#{title} #{tag.i('', class: "fa fa-chevron-#{direction == 'asc' ? 'up' : 'down'}") if css_class.present?}".html_safe,
`html_safe` is a smell of bad code. Don't do this, change that and address your conditional in a block instead 

```ruby
link_to current_page_params.merge({ sort: column, direction: direction }) do
  # whatever
end

2021-04-08 05:50 UTC, thomasstephane commented on app/helpers/application_helper.rb
> +                         "orchestra",
this is messy to fin out what's there, I recommend alpha sorting when the list of params grows like this

2021-04-08 05:50 UTC, thomasstephane commented on app/javascript/controllers/filter_controller.js
> +    return usp.toString()
What is all this for?
I suspect it's a copy paste from somewhere. Break down in small pieces and name the methods so we understand what is happening here.

2021-04-08 05:50 UTC, thomasstephane commented on app/javascript/controllers/filter_controller.js
> +       containerHd.innerHTML = newContainerHd.innerHTML
what is all this for?

2021-04-08 05:50 UTC, thomasstephane commented on app/helpers/application_helper.rb
> +    link_to "#{title} #{tag.i('', class: "fa fa-chevron-#{direction == 'asc' ? 'up' : 'down'}") if css_class.present?}".html_safe,
Furthermore is this really an application helper method? What about using the same name spacing for helper than your view so you know where things are used in?

2021-04-08 05:50 UTC, thomasstephane commented on app/views/videos/index/_filters.html.erb
> +        <%= sortable 'songs.last_name_search', "Orchestra" %>
I can sort by other fields easily by hacking this link. `songs.id` for instance

2021-04-08 07:12 UTC, jmarsh24 commented on app/javascript/controllers/filter_controller.js
> +       containerHd.innerHTML = newContainerHd.innerHTML
This swaps out everything inside of the filters container. I target only what needs to be replaced and leave everything else.

2021-04-08 07:19 UTC, jmarsh24 commented on app/javascript/controllers/filter_controller.js
> +    return usp.toString()
The queryString and usp are used to grab all the current params in the URL.

this.filterTargets passes in the value from either filter or sorting. 

Each one of the values are iterated over and reset in the usp.

The keys for delete, targets keys which are empty. leader_id=&follower_id= in order to keep a clean url.

It also remove undefined, which I haven't figured out why undefined is being passed in 🤔.

Each one of these keys are deleted.

Then the url string is created a returned to the ajax request.

This has some issues regarding the back button. If you have an active search then click on a video and navigate backward it will reload the watch page.

2021-04-08 07:40 UTC, jmarsh24 commented on app/controllers/videos_controller.rb
> +    @videos_paginated = @videos_paginated.shuffle if filtering_params.blank? && sorting_params.blank?
This paginates the videos. If there are not filter/sorting params it shuffles the results so that way when people refresh, the results are always kind of new.

2021-04-08 09:01 UTC, jmarsh24 commented on app/assets/stylesheets/videos/index/filters.scss
> +  height: 315px;
This represents the height of the filter container. Because I'm displaying the filter select in an open state I need to set the height so that way the sorting is spaced properly.

2021-04-10 15:04 UTC, thomasstephane requested changes
The main refactoring piece (the search controller) is still missing, and I still don't see tests :)

2021-04-10 15:04 UTC, thomasstephane commented on app/views/videos/index/_filters.html.erb
> +      <%= render partial: "videos/index/filter_item", locals: { model: @genres, title: :genre, id: 'genre-filter' } %>
why do you call the partial a `filter_item`, isn't just a `filter` ?

Also with the `@search` approach I'm suggesting in your controller here you would have:

```
<%= render partial: "videos/index/filter", locals: { options: @search.genres, title: :genre, id: 'genre-filter' } %>
```

Note the renaming of `model` to `options` that I recommend as you really pass a collection of values to put in your select options

2021-04-12 03:55 UTC, jmarsh24 commented
At the moment, everything regarding filtering/sorting/pagination is working except the back button. If you select a couple of params then press the back button, it updates the url correctly but doesn't actually update the window state.

http://railscasts.com/episodes/246-ajax-history-state

It's basically the issue highlighted in this video. I don't understand how to translate it into Hotwire/stimulus.

2021-04-12 23:29 UTC, jmarsh24 commented
There is a flicker on the font awesome icons each time they appear. When a sorting link is pressed, the arrow shows up in a larger font then is converted down in side. The filter icon also flickers when an ajax action is made.

2021-04-13 02:42 UTC, thomasstephane requested changes

2021-04-13 02:42 UTC, thomasstephane commented on app/assets/stylesheets/videos/index/filters.scss
> +  margin: 0 .5rem .5rem .5rem;
no answer in sight.... Do you know what `rem` is? Is your margin a function of your text size? If not, there is no need to use `rem`.

2021-04-13 02:42 UTC, thomasstephane commented on app/controllers/videos_controller.rb
> +  SEARCHABLE_COLUMNS = %w[
this should live in the `Video::Search` class

2021-04-13 02:42 UTC, thomasstephane commented on app/controllers/videos_controller.rb
> +  def sort_column
this should live in the `Video::Search` class too. `search.sort_column` should probably return it

2021-04-13 02:42 UTC, thomasstephane commented on app/controllers/videos_controller.rb
> +  def sort_direction
Same here

2021-04-13 02:42 UTC, thomasstephane commented on app/controllers/videos_controller.rb
> +  NUMBER_OF_VIDEOS_PER_PAGE = 60
Forgot something in your controller?

2021-04-13 02:42 UTC, thomasstephane commented on app/javascript/controllers/filter_controller.js
> +    let usp = new URLSearchParams(queryString)
usp?

2021-04-13 02:42 UTC, thomasstephane commented on app/javascript/controllers/filter_controller.js
> +    return usp.toString()
what are you doing with all this exactly?

2021-04-13 02:42 UTC, thomasstephane commented on app/models/video/search.rb
> +            shuffle:)
what's with the multiline? Is that a new style? Method def on one line.

2021-04-13 02:42 UTC, thomasstephane commented on app/models/video/search.rb
> +  def all_videos
No, this is the `videos` form the search, all videos is a bad name as this is not all videos.

2021-04-13 02:42 UTC, thomasstephane commented on app/models/video/search.rb
> +  def videos
maybe this is called paginated_videos?

2021-04-13 02:42 UTC, thomasstephane commented on app/models/video/search.rb
> +    all_videos.size - (all_videos.size - (@page * NUMBER_OF_VIDEOS_PER_PAGE).clamp(0, all_videos.size))
this looks awfully complicated. For what? how many videos are shown? Is that just `@page * NUMBER_OF_VIDEOS_PER_PAGE + paginated_videos.size` ?

2021-04-13 02:42 UTC, thomasstephane commented on app/models/video/search.rb
> +  def next_page
memoize.

2021-04-13 02:42 UTC, thomasstephane commented on spec/factories/video/searches.rb
> +  factory :video_search, class: 'Video::Search' do
what is this?

2021-04-13 02:42 UTC, thomasstephane commented on spec/models/video/search_spec.rb
> +  describe "#all_videos" do
Test all the public methods. Each method in its own describe block. This is not the case now.

videos
paginated_videos
displayed_videos_count
next_page
leaders
followers
orchestras
genres
years

Also, your test needs to be organized so it can be reviewed by you furture self (or me). tracking down which test does what is horrible. 

You don't tests for hacking filter or sorts either. Do it, you'll be surprise what nasty things you can do..

2021-04-13 02:42 UTC, thomasstephane commented on spec/models/video/search_spec.rb
> +      it "paginates videos by 60" do
run coverage test on the file, you'll see you're not testing the conditional here

2021-04-13 02:42 UTC, thomasstephane commented on spec/models/video/search_spec.rb
> +        create_list(:video, 150)
must be very slow. DO you really need to create 150 videos to test this? I don't think so.

2021-04-13 02:42 UTC, thomasstephane commented on spec/models/video/search_spec.rb
> +        create_list(:video, 80)
same here, no need for 80. The beauty of a model is that you can create a the instance and set the video to a list of not database saved objects so it's 100x faster.

2021-04-13 02:42 UTC, thomasstephane commented on spec/models/video/search_spec.rb
> +      it "returns leaders options" do
if you test plural, test properly, at least 2 and that 2 videos with same leaders don't duplicate the value in the option list.

2021-04-13 02:42 UTC, thomasstephane commented on spec/models/video/search_spec.rb
> +      describe "#orchestras" do
same here and above

2021-04-13 02:42 UTC, thomasstephane commented on spec/models/video/search_spec.rb
> +      describe "#orchestras" do
copy pasting a bit too much are we?

2021-04-13 02:42 UTC, thomasstephane commented on spec/models/videos_search_spec.rb
>  RSpec.describe VideosSearch, type: :model do
what is this?

2021-04-13 12:04 UTC, jmarsh24 commented on app/javascript/controllers/filter_controller.js
> +    return usp.toString()
This takes the params that's sent from the filter and the current params from the url.

Updates the param value if it exists or appends it to the params.

Parses through the params to find if there is any empty param keys or values

Deletes those values

Returns a params string

Then makes get request and replaces all the filters, videos, and search results.

2021-04-13 12:26 UTC, jmarsh24 commented on spec/factories/video/searches.rb
> +  factory :video_search, class: 'Video::Search' do
I tried to create a factory to clean up repetition in the tests, but just ended up writing them out.

2021-04-13 12:44 UTC, jmarsh24 commented on spec/models/videos_search_spec.rb
>  RSpec.describe VideosSearch, type: :model do
This is a spec to test my materialized view. I was testing the refresh method, but it wasn't working so I removed the code.

2021-04-13 13:31 UTC, jmarsh24 commented on app/models/video/search.rb
> +    all_videos.size - (all_videos.size - (@page * NUMBER_OF_VIDEOS_PER_PAGE).clamp(0, all_videos.size))
This works unless a page is higher than the total amount of videos. I use clamp to limit so the value will never exceed the total amount of videos.

2021-04-14 02:15 UTC, jmarsh24 commented on spec/models/video/search_spec.rb
> +        create_list(:video, 80)
Could you provide an example of what this would look like? I haven't been able to find a good example of how to achieve this.

2021-04-14 15:36 UTC, thomasstephane requested changes
Still need system specs

2021-04-14 15:36 UTC, thomasstephane commented on spec/models/video_spec.rb
> +        event = create(:event, id: 1)
it's generally bad practice to force the id. You can achieve the same this way:

```ruby
event = create(:event)
video = create(:video, event: event)
expect(described_class.filter_by_event_id(event.id)).to eq [video]
```

2021-04-14 15:36 UTC, thomasstephane commented on spec/models/video_spec.rb
> +        channel = create(:channel, id: 1)
don't force the id!

2021-04-14 15:36 UTC, thomasstephane commented on spec/models/video_spec.rb
> +        expect(described_class.filter_by_follower_id(2)).not_to eq [video]
I would make sure the id will not return anything, maybe use a very large number or 0, not a small id that you may accidentally create in your test db

2021-04-14 15:36 UTC, thomasstephane commented on spec/models/video_spec.rb
> +        follower = create(:follower, id: 1)
don't force the id, you don't need that to test the method

2021-04-14 15:36 UTC, thomasstephane commented on spec/models/video_spec.rb
> +        leader = create(:leader, id: 1)
same here

2021-04-14 15:36 UTC, thomasstephane commented on spec/models/video/search_spec.rb
> +  describe "#videos" do
You still have all the other methods under this

2021-04-14 15:36 UTC, thomasstephane commented on app/models/video/search.rb
> +  def next_page
Actually I think this method is never used alone. You always do `.any?` on it, why not creating `next_page?` that does this directly?

Also do you really need to do this? Can't you just check the total display video count versus the total videos?

2021-04-14 15:36 UTC, thomasstephane commented on app/models/video/search.rb
> +  def initialize(filtering_params:, sorting_params:, page:)
I recommend default values here for all 3 values

2021-04-14 15:36 UTC, thomasstephane commented on spec/models/video/search_spec.rb
> +        create_list(:video, 80)
You can force a smaller page number for your purpose: (this assumption default values for you `new` method)

```ruby
it "returns the next page" do
  stub_const("Video::Search::NUMBER_OF_VIDEOS_PER_PAGE", 2)
  create_list(:video, 3)
  page1 = described_class.new(page: 1)
  page2 = described_class.new(page: 2)
  expect(page1.next_page.any?).to eq(true)
  expect(page2.next_page.any?).to eq(false)
end
```

I made a suggestion to change to next_page? which would make this easier.

2021-04-14 15:36 UTC, thomasstephane commented on spec/models/video/search_spec.rb
> +                                         page:             1)
Adding default to the new method will help you clean this up

2021-04-14 15:36 UTC, thomasstephane commented on spec/models/video/search_spec.rb
> +        expect(search_desc.videos).not_to eq [video_a, video_b]
These two `not_to` are redundant, the test above with `eq` verify the equality of the sorting order already.

2021-04-14 15:36 UTC, thomasstephane commented on spec/models/video/search_spec.rb
> +        expect(search_desc.videos).not_to be_nil
same for all the above

2021-04-14 15:36 UTC, thomasstephane commented on spec/models/video/search_spec.rb
> +        expect(search.videos).not_to eq [video_b]
same here and in the example below.

2021-04-14 15:36 UTC, thomasstephane commented on spec/models/video/search_spec.rb
> +      end
Adding the defaults in the `new` method will remove 100 lines easily in these tests

2021-04-14 15:36 UTC, thomasstephane commented on spec/models/video/search_spec.rb
> +        create_list(:video, 61)
mock the number of video per page so you don't need to create crazy lists (2 so it's more than one yet reasonable)

2021-04-14 15:36 UTC, thomasstephane commented on spec/models/video/search_spec.rb
> +        create_list(:video, 61)
same here

2021-04-14 15:36 UTC, thomasstephane commented on spec/models/video/search_spec.rb
> +      it "creates array of leaders and increments multiple videos without duplication" do
this one test also verifies what the other two above are testing, so you can keep this one and ditch the other two to speed up your specs

2021-04-14 15:36 UTC, thomasstephane commented on spec/models/video/search_spec.rb
> +      it "creates array of followers and increments multiple videos without duplication" do
same here

2021-04-14 15:36 UTC, thomasstephane commented on spec/models/video/search_spec.rb
> +      it "creates array of ors and increments multiple videos without duplication" do
and here and below

2021-04-17 04:17 UTC, thomasstephane requested changes

2021-04-17 04:17 UTC, thomasstephane commented on spec/system/videos/index_spec.rb
> +    driven_by(:rack_test)
make this a default in your spec/rails_helper.rb

```ruby
config.before(:each, type: :system) do
  driven_by :rack_test
end
```

2021-04-17 04:17 UTC, thomasstephane commented on spec/system/videos/index_spec.rb
> +  describe "sorts" do
Do you think I would be tired by the time I get here and don't notice there is no tests here?!

2021-04-17 04:17 UTC, thomasstephane commented on spec/system/videos/index_spec.rb
> +      stub_const("Video::Search::NUMBER_OF_VIDEOS_PER_PAGE", 5)
make that 2, create only 2 videos.

2021-04-17 04:17 UTC, thomasstephane commented on spec/system/videos/index_spec.rb
> +      expect(page).to have_content("Displaying 3 Results")
nope. The page should have `Displaying 2 Results` not 3, something is wrong in your test or view here.

2021-04-17 04:17 UTC, thomasstephane commented on spec/system/videos/index_spec.rb
> +      click_on("Load More")
I would test `expect(page).to have_content("Displaying 2 / 3 Results")`

2021-04-17 04:17 UTC, thomasstephane commented on spec/system/videos/index_spec.rb
> +  describe "header" do
You should be testing the feature here. The login should be tested elsewhere. 

The test should look like this:

```ruby
it "shows videos, display and populates filters" do
  setup_videos
  shows_videos
  display_filters
  populate_filters
end

def setup_videos
  create(:video, :display)
  create(:video, :display)
  create(:video, :display)
end

def shows_videos
  visit videos_path
  expect(page).to have_content("probably should test for the video name, and whatever else you should...")
  expect(page).to have_content("Displaying 3 Results")
end

def display_filters
  display_hd_all_buttons
  display_sort_options
end
  
def display_hd_all_buttons
  expect(page).to have_content("HD")
  expect(page).to have_content("All")
end

def display_sort_options
  expect(page).to have_content("Song Title")
  expect(page).to have_content("Orchestra")
  expect(page).to have_content("Channel")
  expect(page).to have_content("View Count")
  expect(page).to have_content("Upload Date")
end

def populate_filters
  # ...
end
```

And so on. This makes it super relabel as to what the scenario you are testing is, tells you which method (and so step in te test) has a problem if it fails, and also has the benefit of setting the test context (create the videos, load chrome headless) only once for testing all the sam behaviors on the page.

2021-04-17 04:17 UTC, thomasstephane commented on spec/models/video/search_spec.rb
> +          VideosSearch.refresh
What is this for?

Your DB is reset no? If this is not cleared for whatever weird reasons, this should be done in the rails_helper as a database cleaning step

2021-04-17 16:14 UTC, jmarsh24 commented on spec/system/videos/index_spec.rb
> +      expect(page).to have_content("Displaying 3 Results")
Should be fixed now. I display the total amount of videos at the top of the page and then the fractional paginated count at the bottom.

2021-04-17 16:16 UTC, jmarsh24 commented on spec/system/videos/index_spec.rb
> +      expect(page).to have_content("Displaying 3 Results")
It's now fixed to only show the results per page if filtering_params are present.

2021-04-17 16:27 UTC, jmarsh24 commented on spec/models/video/search_spec.rb
> +          VideosSearch.refresh
I'm still using the materialized view for the global search (.filter_by_query). VideosSearch.refresh is caching the tsvector column first.

I was having extremely slow queries on global search, 3-10 seconds and with this is significantly less. 

I'm still very lost on how exactly to create a performant full text search, so maybe we stick for this approach for the pull request and look at it later.

Right now, with the materialized view, I think it's the fastest that it's ever going to get.

2021-04-19 17:24 UTC, thomasstephane requested changes

2021-04-19 17:24 UTC, thomasstephane commented on spec/system/videos/index/videos_spec.rb
> +    @event = create(:event, title: "event_title")
Why is this an instance variable? it's not used outside of this method. Are you familiar with [variable scope](https://www.rubyguides.com/2019/03/ruby-scope-binding/)?

2021-04-19 17:24 UTC, thomasstephane commented on spec/system/videos/index/videos_spec.rb
> +    @channel = create(:channel, title: "channel_a")
same here

2021-04-19 17:24 UTC, thomasstephane commented on spec/system/videos/index_spec.rb
> +  def shows_videos
this does more Ethan show videos

2021-04-19 17:24 UTC, thomasstephane commented on spec/system/videos/index_spec.rb
> +    click_on("Popularity")
why do you click twice?

2021-04-19 17:24 UTC, thomasstephane commented on spec/system/videos/index_spec.rb
> +    expect(page).not_to have_css("div.filter-container isHidden")
you might want to use the same selector in the above expect as well.

2021-04-19 17:24 UTC, thomasstephane commented on spec/system/videos/index_spec.rb
> +    filter_by_hd
can you have `filters_correctly` here and have one method test all the filters?

```ruby
def filters_correctly
  filters_by_genre
  filters_by_leader
  # ...
end

def filters_by_genre
  filters_by_genre_alone
  filters_by_genre_and_leader
  # ...
end

def filters_by_genre_alone
  filters_by_genre_a
  expect(video_title_collection).to eq(["video_a"])
  expect(page).to have_current_path("/?genre=genre_a")
end

def filters_by_genre_and_leader
  remove_all_filters
  filters_by_genre_a
  filters_by_leader_a
  expect(video_title_collection).to eq(["video_a"])
  expect(page).to have_current_path("/?genre=genre_a&leader_id=#{@leader.id}")
end

def filters_by_genre_a
  find("div.ss-option", text: "Genre A (1)").click
end

# ...
```

Like this you don't re-create your view 20 times and also test a real interaction of someone clearing filters and searching again. The `remove_all_filters` would effectively be a method that mimics what the user needs to do to clean the filters, so that you don't need to do `visit root_path`.

2021-04-19 17:24 UTC, thomasstephane commented on spec/system/videos/index_spec.rb
> +    visit root_path
what if you ever change your `root_path`? This should be really checking the videos_path

2021-04-19 17:25 UTC, thomasstephane commented
Also, make sure you merge the latest master branch in this so your branch is mergeable again

2021-04-19 18:23 UTC, jmarsh24 commented on spec/system/videos/index_spec.rb
> +    click_on("Popularity")
The popularity is clicked twice because the default is DESC order.

DESC order puts the **view count** by HIGHEST on first click but on **song_title** it sorts videos backward alphabetically.

I wrote my sorting tests to be in alphabetical order. So I click twice for it to default that way.

2021-04-19 18:25 UTC, jmarsh24 commented on spec/models/video/search_spec.rb
> +      srand(3)
This tests the conditional if no sorting/filtering params are present then the results are shuffled. (This prevents the front page from being static).

Shuffle depends on ```sran``` so I'm setting this value so the random result of shuffle is testable.

2021-04-19 18:44 UTC, jmarsh24 commented on spec/system/videos/index_spec.rb
> +    visit root_path
If I run videos path, then all my params will have ```/videos/****=****&****=****```. In the current state, a user never visits the videos_path and instead sees it as a root path.

I had visit videos_path video before, but I thought that this is more applicable to the real world scenario.

2021-04-21 04:31 UTC, jmarsh24 commented on spec/system/videos/index/videos_spec.rb
> +    @event = create(:event, title: "event_title")
If I remove the instance variables, it says that it's missing defined variables.

2021-04-24 16:26 UTC, thomasstephane approved these changes
you still don't reset your filters. This is making all these video index system test slow. You should have a button to do that in the UI and use it in your tests. rest looks alright

2021-05-01 19:33 UTC, thomasstephane requested changes
None of the disabling is tested.

2021-05-01 19:33 UTC, thomasstephane commented on app/assets/stylesheets/videos/index/filters.scss
> +  z-index: 10;
you should centralize your z-index eventually, why 10 and not 11 or 9? not in this PR because it's already doing too much, but in a dedicated PR you should gather all z-index values in one place, and se variables where needed

2021-05-02 15:21 UTC, jmarsh24 commented on app/assets/stylesheets/videos/index/filters.scss
> +  z-index: 10;
Ok. :) I think I'm finally getting the hang of this pull requests. I think all the next ones will be very clean.

2021-05-05 21:20 UTC, thomasstephane requested changes
The 100!!!! file changes here to mostly address rubocop feedback is not helpful. Next time, smaller branches with smaller number of file changes, especially for rubocop changes

2021-05-05 21:20 UTC, thomasstephane commented on db/migrate/000_create_initial_schema.rb
> +class CreateInitialSchema < ActiveRecord::Migration[6.1]
Why is this added in this PR?

2021-05-05 21:20 UTC, thomasstephane commented on db/migrate/20210428220252_add_reviewed_to_playlist.rb
> -class AddReviewedToPlaylist < ActiveRecord::Migration[6.1]
why is this removed?

2021-05-05 21:20 UTC, thomasstephane commented on db/structure.sql
> -('20210428220252');
if you've already ran this in prod you'll have a problem

2021-05-12 01:34 UTC, closed without merging