Global search
jmarsh24/tangodb pull request #22
Opened 2021-04-26 16:17 UTC by jmarsh24

2021-05-01 19:30 UTC, thomasstephane requested changes

2021-05-01 19:30 UTC, thomasstephane commented on db/migrate/20200702183140_create_videos.rb
> +class CreateVideos < ActiveRecord::Migration[6.0]
You can't do that. bringing back all these files is not going to work unless you are destroying your db and restarting, including on Heroku?

If you want to deploy to Heroku and just run rails db:migrate you need to remove all these files and make an initial migration type file like the create_initial_schema file except using the content of your schema.rb file.

2021-05-01 19:30 UTC, thomasstephane commented on db/migrate/20210110182117_postgres_extention_production.rb
> +  ActiveRecord::Base.connection.execute("COMMENT ON EXTENSION plpgsql IS NULL;") if Rails.env.development?
???

2021-05-01 19:30 UTC, thomasstephane commented on db/migrate/20210112175659_add_tsvector_columns_to_videos.rb
> +class AddTsvectorColumnsToVideos < ActiveRecord::Migration[6.1]
and what's all this for?

2021-05-01 19:30 UTC, thomasstephane commented on app/models/video.rb
> +    def filter_by_query(search_string)
this method does too many things, break it down

2021-05-01 19:30 UTC, thomasstephane commented on app/models/video.rb
> +  scope :filter_by_query, ->(search_string) {}
?

2021-05-01 19:30 UTC, thomasstephane commented on app/models/video.rb
> +    def remove_stop_words(str)
what does str stand for?

2021-05-02 05:29 UTC, jmarsh24 commented on db/migrate/20210110182117_postgres_extention_production.rb
> +  ActiveRecord::Base.connection.execute("COMMENT ON EXTENSION plpgsql IS NULL;") if Rails.env.development?
This was me trying to fix the problem when we made the "create_initial_schema" file. I don't think it will be necessary once I switch everything back to ruby.

2021-05-02 05:32 UTC, jmarsh24 commented on db/migrate/20210112175659_add_tsvector_columns_to_videos.rb
> +class AddTsvectorColumnsToVideos < ActiveRecord::Migration[6.1]
<img width="774" alt="image" src="https://user-images.githubusercontent.com/48605824/116803508-19a20c00-aacd-11eb-96e4-aada94010112.png">

This was part of the materialized view full text search which I'm removing in this pull request

2021-05-02 05:32 UTC, jmarsh24 commented on db/migrate/20210112175659_add_tsvector_columns_to_videos.rb
> +class AddTsvectorColumnsToVideos < ActiveRecord::Migration[6.1]
https://pganalyze.com/blog/full-text-search-ruby-rails-postgres

2021-05-05 21:25 UTC, thomasstephane requested changes

2021-05-05 21:25 UTC, thomasstephane commented on db/migrate/20210502054037_create_initial_schema.rb
> +class CreateInitialSchema < ActiveRecord::Migration[6.1]
This will still make prod crash. You need to have all of this collapsed in wan already ran migration otherwise your prod db will try to migrate and file.

2021-05-20 03:22 UTC, thomasstephane approved these changes

2021-05-20 17:10 UTC, merged