Filters Ajax Update - Sorting and HD
jmarsh24/tangodb pull request #23
Opened 2021-04-28 01:31 UTC by jmarsh24

The filters have all been using updating through ajax, but the hd and sorting buttons have been using href links via get request to update the page. The proposed change updates this functionality so that all sorting/filter options function via ajax.

2021-04-29 03:50 UTC, yagudaev commented on spec/system/layouts/application_spec.rb
> +    byebug
byebugs :)

2021-05-01 19:37 UTC, thomasstephane requested changes

2021-05-01 19:37 UTC, thomasstephane commented on app/assets/stylesheets/videos/index/filters.scss
> +  button {
use class name instead of html elements

2021-05-01 19:37 UTC, thomasstephane commented on app/assets/stylesheets/videos/index/filters.scss
> +    svg {
same here

2021-05-01 19:37 UTC, thomasstephane commented on app/helpers/videos_helper.rb
> +        concat title.to_s
Why are you doing this?
Change `sortable(column, title = nil, search)` to `sortable(column, title = "", search)` if you need a default blank string

2021-05-01 19:37 UTC, thomasstephane commented on app/javascript/controllers/filter_controller.js
>    setCurrentParams(searchParams) {
this function now does too many things. break it down

2021-05-01 19:37 UTC, thomasstephane commented on spec/system/layouts/application_spec.rb
> +  def close_filters
not used. 

You still need to clear filter between tests

2021-05-02 07:39 UTC, jmarsh24 commented on spec/system/layouts/application_spec.rb
> +  def close_filters
I should be now testing the closing functionality of the filters.

2021-05-02 18:16 UTC, jmarsh24 commented on spec/system/layouts/application_spec.rb
> +  def close_filters
I think that the filter testing will be much easier now that the other pull request disables the filters on click. The difficult part was targeting a change event each time.

2021-05-05 21:24 UTC, thomasstephane requested changes

2021-05-05 21:24 UTC, thomasstephane commented on spec/system/layouts/application_spec.rb
> +    click_on("TangoTube")
this is not a reset, this is equivalent to `visit root_path`

Reset is clicking the "x" on the filters currently in place

2021-05-05 21:24 UTC, thomasstephane commented on spec/system/videos/index_spec.rb
> +    byebug
remove this!

2021-05-12 01:37 UTC, jmarsh24 commented on spec/system/layouts/application_spec.rb
> +    click_on("TangoTube")
I'm really have a tough time trying to get this to work. Can I just use the visit root_path for now?

I think I may be able to simplify things by using turbo and turning the filter options into href links combined with current_page_params and then just perform normal get requests instead. But I think that would be a separate pull request.

2021-05-20 03:21 UTC, thomasstephane approved these changes

2021-05-20 16:46 UTC, merged