slimselect refactor
jmarsh24/tangodb pull request #3
Opened 2021-02-28 00:01 UTC by jmarsh24

2021-02-28 00:38 UTC, thomasstephane requested changes

2021-02-28 00:38 UTC, thomasstephane commented on app/controllers/videos_controller.rb
> +  def filter
Controller should be RESTful controller, meaning actions in your controller should only be one of `index`, `new`, `create`, `show`, `edit`, `update`, `delete` .

So what does it means if you want just a list of filters? Create a dedicated controller, something like that:

```ruby
# in app/controllers/videos/filters_controller.rb
class Videos::FiltersController < ApplicationController
  def index
    # Your filters go here
  end
end
```

So in your routes:

```ruby
namespace :videos do
  resources :filters, only: :index
end
```

2021-02-28 00:38 UTC, thomasstephane commented on app/controllers/videos_controller.rb
> +  def filter_videos
In the MVC approach (Model View Controller) which is what rails is, you want your controller as simple as possible and move the complexity in your models. So here, the controller for filters should be very simple, something like that:

```ruby
# in app/controllers/videos/filters_controller.rb
class Videos::FiltersController < ApplicationController
  def index
    render json: Video::Filter.where(filter_params)
  end
end
```

And then you create a model `Video::Filter` that returns your filters.

```ruby
class Video::Filter
  class << self
    def where(params)
      # your code goes here
    end
  end
end
```

2021-02-28 00:38 UTC, thomasstephane commented on app/javascript/controllers/filter_controller.js
> +     type: "post",
Probably doesn't need to be a `post` here? the suggestion I gave earlier request a `get`.

2021-02-28 00:38 UTC, thomasstephane commented on app/controllers/videos_controller.rb
> +      video: render_to_string(partial: 'videos/index/videos', layout: false)
you're conflating filters and video searching here. you should have 2 different routes, one that updates the filter one that update the videos. Remove this. 

Also, very bad practice to pass your html as json like this. Using Hotwire turbo frames is a much better approach here.

2021-02-28 00:38 UTC, thomasstephane commented on app/controllers/videos_controller.rb
> +    @videos_total = Video.all.where(hidden: false).size
What is this for? The paginate gem you are sing return the total number of elements anyways.

2021-02-28 00:38 UTC, thomasstephane commented on app/controllers/videos_controller.rb
> +    @genres = @videos.joins(:song).pluck('songs.genre').uniq.compact.sort.map(&:titleize).uniq.map do |text|
I don't think tit's a good UX to filter the filter based on what is available. By doing this you can't really expand back from one filter to another. Either have people filter one thing at a time and condition the next filter (bad UX I think for you) or let them filter with whatever, but don't filter the filter based on another filter. It is necessary complex, and as a user I can only reset all filters to really go anywhere. Pretty bad UX.

2021-02-28 00:38 UTC, thomasstephane commented on app/controllers/videos_controller.rb
> +    @orchestras = @videos.joins(:song).pluck('songs.artist').uniq.compact.sort.map(&:titleize).map do |text|
So all these go away and you can just have simple filters.

2021-02-28 00:38 UTC, thomasstephane commented on app/javascript/controllers/slimselect_controller.js
> +    if (this.slimselect) {
why would this be false if you only initialize this controller for the view that has it?

2021-02-28 00:38 UTC, thomasstephane commented on app/javascript/controllers/filter_controller.js
> +    //    history.pushState({}, '', `${window.location.pathname}?${this.params}`)
remove commented code.

2021-02-28 00:38 UTC, thomasstephane commented on app/javascript/controllers/slimselect_controller.js
> +      this.dataInitialize()
you don't initialize any data, you initialize your selects. Rename this so that in 6 months when you re-read this method name you understand what it actually does.

2021-02-28 00:38 UTC, thomasstephane commented on app/views/videos/index/_filter_item.html.erb
> -  <%= select_tag title.to_s,
why moving away from select tag?

2021-02-28 00:38 UTC, thomasstephane commented on config/routes.rb
> +  post '/videos/filter', to: 'videos#filter'
See other comment, this is a bad idea

2021-03-06 18:36 UTC, shivamd commented
🍔

2021-04-13 02:48 UTC, closed without merging