Refactor video model: Youtube_Import
jmarsh24/tangodb pull request #4
Opened 2021-02-28 21:21 UTC by jmarsh24

I have updated the following files.

The files here are updated and ready for preliminary review to check my general direction:
/app/models/video/youtube_import.rb
/app/models/video/youtube_import/**

I also moved the audio content recognition(acrcloud), YouTube-dl, ffmpeg, and Spotify to their own folders. I figured each service should have it's own folder?

/app/models/video.rb

I refactored the logic for the scope/dancer matching. Should all these matcher scripts be put into some sorting string matching model?

2021-02-28 22:31 UTC, thomasstephane requested changes

2021-02-28 22:31 UTC, thomasstephane commented on app/models/video/youtube_import/channel.rb
> +    @channel = Channel.create(to_channel_params)
So you need to add `import_videos` in this method

2021-02-28 22:31 UTC, thomasstephane commented on app/models/video/youtube_import/channel.rb
> +    def import_videos(channel_id)
you don't need this

2021-02-28 22:31 UTC, thomasstephane commented on app/models/video/youtube_import/channel.rb
> +    @channel = channel
You don't need that, this is not part of the initialize, but rather the result of import.

2021-02-28 22:31 UTC, thomasstephane commented on app/models/video/youtube_import/channel.rb
> +  def channel_videos
this is not channel videos, but rather `channel_existing_youtube_video_ids`

2021-02-28 22:31 UTC, thomasstephane commented on app/models/video/youtube_import/channel.rb
> +    @channel.videos.map(&:youtube_id).to_a
`@channel.videos.pluck(&:youtube_id).uniq` is probably a faster way to do this. Also do you have an index on this column?

2021-02-28 22:31 UTC, thomasstephane commented on app/models/video/youtube_import/channel.rb
> +  def youtube_channel_videos
So this should be youtube_channel_video_ids

2021-02-28 22:31 UTC, thomasstephane commented on app/models/video/youtube_import/channel.rb
> +  def channel
not needed

2021-02-28 22:31 UTC, thomasstephane commented on app/models/video/youtube_import/channel.rb
> +    `youtube-dl https://www.youtube.com/channel/#{channel_id}/videos  --get-id --skip-download`.split
You need to handle what happen if the api fails. I suggest some logging at least.
I would also separate the YouTube dl call from its parsing (the "split" method). So it doesn't break, something like that:

```ruby
def get_channel_video_ids(channel_id)
  get_channel_videos(channel_id).split
end

def get_channel_videos(channel_id)
  `youtube-dl https://www.youtube.com/channel/#{channel_id}/videos  --get-id --skip-download`
rescue => e
  Rails.logger.warn "Video::YoutubeImport::Channel youtube-dl video fetching error: #{e.backtrace.join("\n\t")}"
  "" # note the empty string return so your split method works always.
end
```

2021-02-28 22:31 UTC, thomasstephane commented on app/models/video/youtube_import/playlist.rb
> +    def import_channels(playlist_id)
you don't need this or the previous one

2021-02-28 22:31 UTC, thomasstephane commented on app/models/video/youtube_import/playlist.rb
> +    @playlist = Playlist.create(to_playlist_params)
So after that you can do `import_videos` here

2021-02-28 22:31 UTC, thomasstephane commented on app/models/video/youtube_import/playlist.rb
> +  def import_channels
not used

2021-02-28 22:31 UTC, thomasstephane commented on app/models/video/youtube_import/playlist.rb
> +    Video.all.map(&:youtube_id).to_a
same comment as before here and for your method names in this file.

2021-02-28 22:31 UTC, thomasstephane commented on app/models/video/youtube_import/video.rb
> +    Video.create(to_video_params)
I would check if the video already exist first. You don't want to accidentally re-create an existing one.

2021-02-28 22:31 UTC, thomasstephane commented on app/models/video/youtube_import/video.rb
> +    Channel.find_by(channel_id: @youtube_video.channel_id)
what if you don't find it? Should you create it?

2021-02-28 22:31 UTC, thomasstephane commented on config/application.rb
> +require "json"
Why? Isn't all this included automatically?

2021-02-28 22:31 UTC, thomasstephane commented on db/seeds.rb
> +CSV.foreach('data/tangodb-datasets/el_recodo_songs.csv', headers: true) do |column|
I refuse to review this, this is bad practice and you shouldn't do that :) Same for Beth rest of your seed files.

2021-02-28 22:31 UTC, thomasstephane commented on app/workers/import_video_worker.rb
> +    Video::YoutubeImport::Video.import(youtube_id)
Do `Video::YoutubeImport.from_video(youtube_id)` instead here. Looks the same but if you add logic to the import tomorrow you shouldn't need to change this

2021-02-28 22:31 UTC, thomasstephane commented on app/models/video/youtube_dl/youtube_dl_import.rb
> +class Video::YoutubeImport::Video
What is this whole file? It won't be autoloaded (name of the file doesn't match the class name) and it's a duplicated name of the one you re-define later.

I did not review the rest of this file because I don't think this was intended, but if it is these methods are wayyy too big and need to be broken apart.

2021-02-28 22:31 UTC, thomasstephane commented on app/models/video/acr_cloud/acr_cloud_import.rb
> +    # accepts file path and submits a http request to ACR Cloud API
Does it? I can't tell. 
Do the same as for the `Video::YoutubeImport::Video` : create an instance of your class and do smaller steps in dedicated methods. This is a mess of things impossible to read for me today and for you soon enough.

2021-02-28 22:31 UTC, thomasstephane commented on app/models/video/acr_cloud/acr_cloud_import.rb
> +      requrl = "http://identify-eu-west-1.acrcloud.com/v1/identify"
things like that should be class constants, for instance: 

```ruby
ACR_CLOUD_URL = "http://identify-eu-west-1.acrcloud.com/".freeze
ACR_CLOUD_IDENTITY_API_ENDPOINT = "/v1/identify".freeze
```

2021-02-28 22:31 UTC, thomasstephane commented on app/models/video/acr_cloud/acr_cloud_import.rb
> +      string_to_sign = http_method + "\n" + http_uri + "\n" + access_key + "\n" + data_type + "\n" + signature_version + "\n" + timestamp
bad name for variables all around here

2021-02-28 22:31 UTC, thomasstephane commented on app/models/video/acr_cloud/acr_cloud_import.rb
> +    end
way too much going on in this method. One method one action performed.

2021-02-28 22:31 UTC, thomasstephane commented on app/models/video/acr_cloud/acr_cloud_import.rb
> +    rescue StandardError
Yeah... I'm not gonna review the details of this monstrosity of a method :) 

Break it down in smaller methods so one can follow what on each is happening here.

2021-02-28 22:31 UTC, thomasstephane commented on app/models/video/acr_cloud/acr_cloud_import.rb
> +end
indentation is all over the place too. Run rubocop on your files!

2021-02-28 22:31 UTC, thomasstephane commented on app/models/video/acr_cloud/acr_cloud_import.rb
> +    def clip_audio(youtube_id)
all the methods on this file need refactor. Too much going on, bad naming

2021-02-28 22:36 UTC, thomasstephane commented
Also, HUGE issue: where on earth is your schema file? It's no longer in the repo!!
Run rails db:migrate and commit your db/schema.rb

2021-02-28 22:47 UTC, jmarsh24 commented on app/models/song.rb
> +      Song.column_defaults["occur_count"]
They are supposed to reset the popularity and occur_count back to 0. That way it can recalculate the values and update them.

2021-02-28 22:47 UTC, jmarsh24 commented on app/models/channel.rb
> +      Channel.where(imported: false).order(:id).each do |channel|
I had it order by id just to keep track.  Mostly for diagnostics so I had an idea which channel was being imported if it failed.

2021-02-28 22:48 UTC, jmarsh24 commented on app/models/channel.rb
> +      Channel.where('imported_videos_count < total_videos_count').each do |channel|
Is there a reason you prefer double quotes in this case? There is no interpolation going on.

2021-02-28 22:58 UTC, jmarsh24 commented
I think I lost my schema.rb file when I introduced a materialized view for my global search. 🤔

2021-02-28 23:40 UTC, thomasstephane commented on app/models/channel.rb
> +      Channel.where('imported_videos_count < total_videos_count').each do |channel|
it's a better default in case you'll interpolate. run rubocop should return no errors

2021-02-28 23:40 UTC, thomasstephane commented on app/models/channel.rb
> +      Channel.where(imported: false).order(:id).each do |channel|
then remove it, you're slowing it down, let the db return its default order

2021-02-28 23:41 UTC, thomasstephane commented on app/models/song.rb
> +      Song.column_defaults["occur_count"]
They don't, they just list the default.

2021-02-28 23:42 UTC, thomasstephane commented
> I think I lost my schema.rb file when I introduced a materialized view for my global search. 🤔

Bring it back. Pretty sure your rails app will fail if you don't

2021-03-01 06:44 UTC, jmarsh24 commented on app/models/channel.rb
> +      Channel.where('imported_videos_count < total_videos_count').each do |channel|
I was thinking the opposite in order to prevent any possibility of sql injection into the code. I will change it though. :)

2021-03-01 07:17 UTC, jmarsh24 commented on app/models/video/acr_cloud/acr_cloud_import.rb
> +end
done.

2021-03-01 07:54 UTC, jmarsh24 commented
I figured it out. When I created my Postgres materialized view for full text search, I can no longer use the database agnostic schema.rb. The information is now located in a structure.sql file.

2021-03-01 16:07 UTC, thomasstephane commented
> I figured it out. When I created my Postgres materialized view for full text search, I can no longer use the database agnostic schema.rb. The information is now located in a structure.sql file.

I don't like it. I suspect this will bite back. What does materialized view gives you exactly?

2021-03-01 16:55 UTC, jmarsh24 commented
Full text search creates normalizes the words compared to a dictionary you give it so that way you can search on root words(natural language). A view allows you to basically link multiple a tables as if they are one. Each time it searches the view it has to to generate a normalized pattern to search across. A materialized view is basically a large table stored in memory that's refreshed however often you specify. But since it doesn't have to do all the joins and generate this normalized search it's supposed to be extremely fast.

It's a new feature in Postgres and  supposed to mimic what you get from using elastic search or algolia full text search.

It also allows you to create fuzzy strings tables that allow you to misspell words and still get the results. It caches these so that way it's still really fast. The trade off is that it's not database agnostic and only works with Postgres at the moment.

2021-03-03 21:05 UTC, merged

2021-03-06 18:28 UTC, thomasstephane commented on app/models/song.rb
> +  has_many :videos, dependent: :destroy
do you understand what this does?

2021-03-06 18:28 UTC, thomasstephane commented on app/models/song.rb
>      def scrape_lyrics
This should be its own subclass. Ok not to address now as you're just fixing the rubocop comments but this is very flimsy and will break.

2021-03-06 18:28 UTC, thomasstephane commented on app/models/song.rb
> +      max_value = occur_num.values.max
not addressed!

2021-03-06 18:28 UTC, thomasstephane commented on app/models/song.rb
> +      popularity = occur_num.transform_values { |v| (v.to_f / max_value * 100).round }
not addressed!

2021-03-06 18:28 UTC, thomasstephane commented on app/models/song.rb
> +      occur_num.each do |key, value|
not addressed!

2021-03-06 18:28 UTC, thomasstephane commented on app/models/song.rb
> +        song.update(occur_count: value)
not addressed!

2021-03-06 18:28 UTC, thomasstephane commented on app/models/song.rb
> +      end
not addressed!

2021-03-06 18:28 UTC, thomasstephane commented on app/models/video/music_recognition/acr_cloud/client.rb
> +  def send_audio_file
this needs refactor. Break each step in its own method. I don't care tat in the ACR gem is lays it like that, this is not clean and you need to understand it when reading again. It's easy to break down.

2021-03-06 18:28 UTC, thomasstephane commented on app/models/video/music_recognition/acr_cloud/parse.rb
> +    if parsed_data.deep_find("spotify").present?
should be its own method

2021-03-06 18:28 UTC, thomasstephane commented on app/models/video/youtube_import.rb
> +      Playlist.import_videos(playlist_id)
not addressed!

2021-03-06 18:28 UTC, thomasstephane commented on app/models/video/youtube_import/playlist.rb
> +    def import_channels(playlist_id)
not addressed!

2021-03-06 18:28 UTC, thomasstephane commented on app/models/video/youtube_import/playlist.rb
> +    @playlist = Playlist.create(to_playlist_params)
not addressed!

2021-03-06 18:28 UTC, thomasstephane commented on app/models/video/youtube_import/playlist.rb
> +  def import_channels
not addressed!

2021-03-06 18:28 UTC, thomasstephane commented on app/models/video/youtube_import/playlist.rb
> +    Video.all.map(&:youtube_id).to_a
not addressed!

2021-03-06 20:31 UTC, jmarsh24 commented on app/models/song.rb
>      def scrape_lyrics
At the moment, I only need to do this once. In the future, I may want to have some sort of web hook that updates my database whenever something changes. or I scan the database for lyrics updates or corrections.

I'm not sure at the moment how to make it more robust 🤔

2021-03-06 20:39 UTC, jmarsh24 commented on app/javascript/controllers/loadmore_controller.js
> +  export default class extends Controller {
I will move this pull request for after the new filters are complete.

2021-03-06 22:19 UTC, jmarsh24 commented on app/models/ahoy/visit.rb
> +  self.primary_key = "id"
This is a fix for a problem I was facing with ahoy. I found that this fixed the issue.

<img width="1254" alt="image" src="https://user-images.githubusercontent.com/48605824/110222429-56d58d80-7ed2-11eb-89e1-786e1563610c.png">

2021-03-07 19:45 UTC, jmarsh24 commented
Are you trying to highlight the that playlist should be broken up into import_videos, import_channels, and import seperately?