General refactor
jmarsh24/tangodb pull request #5
Opened 2021-03-06 19:48 UTC by jmarsh24

2021-03-07 20:12 UTC, thomasstephane requested changes

2021-03-07 20:12 UTC, thomasstephane commented on app/models/web_scrape.rb
> +      end
Here is what I would do for this parsing:

```ruby
# in app/models/song/recodo_lyrics.rb

class Song::RecodoLyrics
  WHATEVER_20_000_REPRESENTS = 20_000 # your obviously want to rename this constant

  class << self
    delegate :fetch, to: :new
  end

  def fetch
    (1..WHATEVER_20_000_REPRESENTS).each do |id|
      fetch_page(id)
    end
  end

  private

  def fetch_page(id)
    logger.info "Page Number: #{id}"

    page = Page.new(id: id)
    page.update_song_from_lyrics
  end
end
```

```ruby
# app/models/song/recodo_lyrics/page.rb

class Song::RecodoLyrics::Page
  RECODO_URL_PREFIX = "https://www.el-recodo.com/music?id=".freeze
  RECODO_URL_SUFFIX = "&lang=en".freeze
  RECODO_LYRICS_HTML_MARKER = "p#geniusText".freeze
  RECODO_METADATA_HTML_MARKER = "div.list-group.lead a".freeze

  def initialize(id)
    @id = id
  end

  def update_song_from_lyrics
    return if lyrics.blank?
    song = ::Song.where("title ILIKE ? AND artist ILIKE ?", title, artist).first
    return unless song
    song.update(el_recodo_song_id: @id, lyrics: lyrics)
  end

  private

  def artist
    return if metadata[3].blank?
    @artist ||= metadata[3].text.strip.split[1..].join(" ")
  end

  def title
    return if metadata[1].blank?
    @title ||= metadata[1].text.strip.split[1..].join(" ")
  end

  def metadata
    @metadata ||= parsed_body.css(RECODO_METADATA_HTML_MARKER)
  end

  def lyrics
    @lyrics ||= parsed_body.css(RECODO_LYRICS_HTML_MARKER).try(:text)
  end

  def parsed_body
    @parsed_body ||= ::Nokogiri::HTML(raw.body)
  end

  def raw
    ::Faraday.get(RECODO_URL_PREFIX + @id + RECODO_URL_SUFFIX)
  end
end
```

And you can do the fetching by calling `Song::RecodoLyrics.fetch`

2021-03-07 20:12 UTC, thomasstephane commented on app/models/web_scrape.rb
> +    def tangopolix_events
I let you do this one based on the recodo example.

2021-03-07 20:12 UTC, thomasstephane commented on app/models/video/music_recognition/acr_cloud/client.rb
> +    set_sample_size
not sure the initialize need to do all this, the `call` (bad name :) ) should do what it needs. Check my suggestion on the lyrics for a better way to improve this.

2021-03-07 20:12 UTC, thomasstephane commented on app/models/video/music_recognition/acr_cloud/parse.rb
> +    parse_spotify_data
Same here

2021-03-07 20:16 UTC, jmarsh24 commented on app/models/web_scrape.rb
> +      end
Is there a way for me to determine how many pages there are? I choose 20,000 because I figured that there shouldn't be more pages than that. There are some gaps in his ID pages and he has about 15,106 recordings.

2021-03-07 20:28 UTC, jmarsh24 commented on config/environments/test.rb
> +  ActiveSupport::Deprecation.silenced = true
Do you have an idea of what exactly I need to change. I wasn't sure if this is a problem that was brought on by Hotwire. 🤔 I didn't really see any info online on how to fix it.

2021-03-07 20:32 UTC, jmarsh24 commented on db/migrate/20210306201925_add_el_recodo_song_id.rb
> +    add_column :songs, :el_recodo_song_id, :int
This el_recodo_song_id is put there so that way I can reference visit the page at later point in case there is an update to the database. I don't plan to use it for searching. Should I add it anyway?

2021-03-07 20:38 UTC, jmarsh24 commented on spec/models/follower_spec.rb
> +    it 'tests full_name to return "first_initial. last_name"' do
Do you prefer using these fixtures over a factory?

2021-03-07 22:53 UTC, thomasstephane commented on config/environments/test.rb
> +  ActiveSupport::Deprecation.silenced = true
Remove it and see what the warning says:

```
===========================================
 DEPRECATION: The cocaine gem is deprecated. Please upgrade to terrapin. See https://github.com/thoughtbot/terrapin/ for further instructions.
===========================================
```

That is self explanatory, remove that. I know the YouTube-dl gem brings it, submit a change their that uses terrapin.

```
DEPRECATION WARNING: Initialization autoloaded the constants ApplicationHelper, ChannelsHelper, EventsHelper, FollowersHelper, LeadersHelper, PlaylistsHelper, SearchSuggestionsHelper, SongsHelper, StaticPagesHelper, UsersHelper, WatchHelper, Stimulus::StimulusHelper, FontAwesome::Rails::IconHelper, DeviseHelper, ApplicationController, ActionText::ContentHelper, and ActionText::TagHelper.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload ApplicationHelper, for example,
the expected changes won't be reflected in that stale Module object.

These autoloaded constants have been unloaded.

In order to autoload safely at boot time, please wrap your code in a reloader
callback this way:

    Rails.application.reloader.to_prepare do
      # Autoload classes and modules needed at boot time here.
    end

That block runs when the application boots, and every time there is a reload.
For historical reasons, it may run twice, so it has to be idempotent.

Check the "Autoloading and Reloading Constants" guide to learn more about how
Rails autoloads and reloads.
 (called from <top (required)> at /Users/stephanethomas/Documents/Coding/Projects/tangodb/config/environment.rb:5)
===========================================
 DEPRECATION: The cocaine gem is deprecated. Please upgrade to terrapin. See https://github.com/thoughtbot/terrapin/ for further instructions.
===========================================
DEPRECATION WARNING: Initialization autoloaded the constants ApplicationHelper, ChannelsHelper, EventsHelper, FollowersHelper, LeadersHelper, PlaylistsHelper, SearchSuggestionsHelper, SongsHelper, StaticPagesHelper, UsersHelper, WatchHelper, Stimulus::StimulusHelper, FontAwesome::Rails::IconHelper, DeviseHelper, ApplicationController, ActionText::ContentHelper, and ActionText::TagHelper.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload ApplicationHelper, for example,
the expected changes won't be reflected in that stale Module object.

These autoloaded constants have been unloaded.

In order to autoload safely at boot time, please wrap your code in a reloader
callback this way:

    Rails.application.reloader.to_prepare do
      # Autoload classes and modules needed at boot time here.
    end

That block runs when the application boots, and every time there is a reload.
For historical reasons, it may run twice, so it has to be idempotent.

Check the "Autoloading and Reloading Constants" guide to learn more about how
Rails autoloads and reloads.
 (called from <main> at /Users/stephanethomas/Documents/Coding/Projects/tangodb/config/environment.rb:5)
 set_config
------------
```

This is the same message twice, meaning you have two offenders, the first on environment.rb which I'm pretty sure you don't need:

```ruby
Rails.application.reloader.to_prepare do
  # Autoload classes and modules needed at boot time here.
end
```

The other one I suspect come from an initializer, perhaps ahoy? Google it you'll see there are some [answers](https://stackoverflow.com/questions/56402093/how-can-i-preload-concerns-in-a-rails-initializer-using-rails-6-zeitwerk).

2021-03-07 22:53 UTC, thomasstephane commented on db/migrate/20210306201925_add_el_recodo_song_id.rb
> +    add_column :songs, :el_recodo_song_id, :int
No that's fine

2021-03-07 22:54 UTC, thomasstephane commented on spec/models/follower_spec.rb
> +    it 'tests full_name to return "first_initial. last_name"' do
no, this use neither. factory is better for more complex models, fixtures for smaller interactions, both have pros & cons

2021-03-07 23:04 UTC, thomasstephane requested changes

2021-03-07 23:04 UTC, thomasstephane commented on spec/models/leader_spec.rb
>    context "method tests" do
useless

2021-03-07 23:04 UTC, thomasstephane commented on app/models/web_scrape.rb
> +    def tangopolix_events
this is not done yet

2021-03-07 23:04 UTC, thomasstephane commented on spec/models/follower_spec.rb
> +      expect(follower.reviewed).to include(follower)
Also, this should be a shared example too: `it_behaves_like "a reviewable", :follower`

```ruby
RSpec.shared_examples "a reviewable" do |factory_name|
  describe ".reviewed" do
    it "includes objects with reviewed flagged" do
      reviewed = create(factory_name, reviewed: true)
      unreviewed = create(factory_name, reviewed: false)
      expect(described_class.reviewed).to include(reviewed)
      expect(described_class.reviewed).not_to include(unreviewed)
    end
  end
 end
```

And in leader: `it_behaves_like "a reviewable", :leader`

2021-03-07 23:31 UTC, merged

2021-03-08 08:59 UTC, jmarsh24 commented
trying to reopen the pull request 🤦‍♂️

2021-03-08 09:06 UTC, jmarsh24 commented
trying to reopen the pull request 🤦‍♂️

2021-03-08 16:50 UTC, jmarsh24 commented on config/environments/test.rb
> +  ActiveSupport::Deprecation.silenced = true
I figured it out. It was a problem with the gorails episode on how to fix the form errors that turbo causes when you use it with devise.

2021-03-08 22:47 UTC, jmarsh24 commented on app/models/web_scrape.rb
> +      (1..20_000).each do |id|
There are 15,000 songs in the database and there are some gaps in the id's. 20,000 seemed like an interval large enough that would encapsulate all the possible pages in the database.

2021-03-09 16:13 UTC, jmarsh24 commented on spec/models/follower_spec.rb
> +      expect(follower.reviewed).to include(follower)
for some reason when I run the test I'm receiving 

`1) Follower behaves like a reviewable .reviewed includes objects with reviewed flagged
     Failure/Error: reviewed = create(factory_name, reviewed: true)

     KeyError:
       Factory not registered: nil
     Shared Example Group: "a reviewable" called from ./spec/models/follower_spec.rb:20
     # ./spec/support/models/shared_examples/reviewable.rb:4:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # KeyError:
     #   key not found: nil
     #   ./spec/support/models/shared_examples/reviewable.rb:4:in `block (3 levels) in <top (required)>'

Finished in 0.09752 seconds (files took 4.95 seconds to load)
15 examples, 1 failure`