Current WIP
jmarsh24/tangodb pull request #7
Opened 2021-03-11 15:37 UTC by jmarsh24

This pull request incorporated changes in both
 [**General refactor**](https://github.com/jmarsh24/tangodb/pull/5)
 [**Refactor video model: Youtube_Import**](https://github.com/jmarsh24/tangodb/pulls?q=is%3Apr+is%3Aclosed)

2021-03-11 17:23 UTC, thomasstephane requested changes

2021-03-11 17:23 UTC, thomasstephane commented on app/models/concerns/displayable.rb
> +module Displayable
Interesting approach here, but this is very much video specific. So it's a good idea to extra the view components in a sub class, but I think this should be namespaced under `Video::` and in the `app/models/video/` folder.

Something like that:

```ruby
# in app/models/video/display.rb
class Video::Display
  def initialize(video)
    @video = video
  end

  # all your methods go here
end
```

And then in video model:

```ruby
def display
  @display  ||= Video::Display.new(self)
end
```

So that in your views you can do:

```ruby
video.display.dancer_names
```

2021-03-11 17:23 UTC, thomasstephane commented on app/models/concerns/full_nameable.rb
> +    [first_name.first, last_name].compact.map(&:titleize).join(". ") if first_name.present? && last_name.present?
Actually, this is making the method slower. You create an array, of text you iterate over and then join. In a large scale, this is far slower than string extrapolation.

I would do:

```ruby
def abrev_name
  return "" if first_name.blank? || last_name.blank?
  "#{first_name.try(:first).capitalize}. #{last_name.capitalize}"
end
```

Also note that your "compact" is useless as you check first that both are present.

2021-03-11 17:23 UTC, thomasstephane commented on app/models/concerns/full_nameable.rb
> +    abrev_name.delete(" ") if abrev_name.present?
`abrev_name.try(:delete, " ")`

2021-03-11 17:23 UTC, thomasstephane commented on app/models/event/tangopolix_events.rb
> +class Event::TangopolixEvents
Are you using this anywhere?

Not sure about the naming, are you fetching only? I would do `Event::Tangopolix.fetch`, `Events` feels redundant

2021-03-11 17:23 UTC, thomasstephane commented on app/models/playlist.rb
> +  scope :not_reviewed, ->   { where(reviewed: false) }
use the reviewable concern!

2021-03-11 17:23 UTC, thomasstephane commented on app/models/song.rb
> +      @counts_of_videos_by_song_id.transform_values { |v| (v.to_f / @counts_of_videos_by_song_id * 100).round }
` @counts_of_videos_by_song_id` doesn't exist. Did you mean `count_of_videos_for_most_popular_song` ?

Also, don't use `|v|`, use a real name of what it is `videos_count` maybe?

2021-03-11 17:23 UTC, thomasstephane commented on app/models/song.rb
> +      counts_of_videos_by_song_id.each do |key, value|
not `key` `value` but `song_id` and `videos_count`

2021-03-11 17:23 UTC, thomasstephane commented on app/models/song.rb
> +      generate_popularity_value_of_each_song.each do |key, value|
same here

2021-03-11 17:23 UTC, thomasstephane commented on app/models/video.rb
> +  belongs_to :event, optional: true, counter_cache: true
👍

2021-03-11 17:23 UTC, thomasstephane commented on app/models/video/music_recognition.rb
>      def from_video(youtube_id)
`from_video` makes me belive that this is from a video object. this is `from_youtube_id` instead here

2021-03-11 17:23 UTC, thomasstephane commented on app/models/video/music_recognition.rb
> +      Youtube.fetch(youtube_id)
Why do you re-fetch from YouTube here?

2021-03-11 17:23 UTC, thomasstephane commented on app/models/video/music_recognition/acr_cloud.rb
>      @video = Video.find_by(youtube_id: youtube_id)
I recommend adding an handler if you don't find the video, to either create if you don't find it, or return an error.

2021-03-11 17:23 UTC, thomasstephane commented on app/models/video/music_recognition/acr_cloud/audio.rb
> +  def time1
very bad name. what is time1? a start time? a start sample time?

2021-03-11 17:23 UTC, thomasstephane commented on app/models/video/music_recognition/acr_cloud/client.rb
> +  def send_audio_file_to_acr_cloud
isn't this more of a get audio from acr cloud? the method returns a response from it

2021-03-11 17:23 UTC, thomasstephane commented on app/models/video/music_recognition/acr_cloud/client.rb
> +  REQ_URL = "http://identify-eu-west-1.acrcloud.com/v1/identify".freeze
This is good, I recommend namespacing this with `ACR_CLOUD_` because if you have other  `HTTP_METHOD` or `ACCESS_KEY` for other models that might conflict

2021-03-11 17:23 UTC, thomasstephane commented on app/models/video/music_recognition/youtube.rb
>      def from_video(youtube_id)
Same here, bad naming

2021-03-11 17:23 UTC, thomasstephane commented on app/models/video/youtube_import/channel.rb
> +    `youtube-dl https://www.youtube.com/channel/#{@channel_id}/videos  --get-id --skip-download`.split
Constants for this

2021-03-11 17:23 UTC, thomasstephane commented on app/views/videos/show/_video_info_primary.html.erb
> +    <%= formatted_metadata(@video) %>
nice cleaning

2021-03-11 17:23 UTC, thomasstephane commented on data/tangodb-datasets/Events.csv
> -,Name
all this css are a mistake. but probably not worth fixing in that PR>

2021-03-11 21:15 UTC, thomasstephane requested changes

2021-03-11 21:15 UTC, thomasstephane commented on app/models/video/youtube_import/channel.rb
> +YOUTUBE_DL_COMMAND = "youtube-dl https://www.youtube.com/channel/#{@channel_id}/videos  --get-id --skip-download".freeze
Constant shouldn't have variables. Create 2 constants for prefix/suffix instead. `@channel_id` here is a class variable call, which is nil.

2021-03-11 21:15 UTC, thomasstephane commented on app/models/video/youtube_import/channel.rb
> +    @channel = Channel.create(to_channel_params) if @channel.blank?
the 2 chancels here are the same thing no?

```ruby
def import
  if @channel.present?
    @channel.update(to_channel_params)
  else
    @channel = Channel.create(to_channel_params)
  end
end
```

2021-03-11 21:15 UTC, thomasstephane commented on app/models/video/youtube_import/channel.rb
> +  def channel
memoize this so you don't go to the DB everytime you call it.

```ruby
def channel
  @channel ||= Channel.find_by(channel_id: @channel_id)
end
```

So you can also change other methods: 

```ruby
def import
  if channel.present?
    channel.update(to_channel_params)
  else
    @channel = Channel.create(to_channel_params)
  end
end
```

2021-03-11 21:15 UTC, thomasstephane commented on videos_seeds.rb
> +Video.create({"title"=>"Astor Piazzolla - 100th Anniversary | Bandonegro / Dawid Kostka / Agnieszka Stach & Tymoteusz Ley", "youtube_id"=>"aHcLacNV0-s", "leader_id"=>nil, "follower_id"=>nil, "descrip
What is this?!

2021-03-11 21:55 UTC, jmarsh24 commented on app/controllers/turbo_controller.rb
> +class TurboController < ApplicationController
This is from GoRails to allow turbo to work with devise. 

https://gorails.com/episodes/devise-hotwire-turbo

2021-03-11 21:55 UTC, jmarsh24 commented on app/controllers/turbo_controller.rb
> +class TurboController < ApplicationController
This was causing the depreciation error when I tried to run Rspec

2021-03-11 22:16 UTC, jmarsh24 commented on app/models/event/tangopolix_events.rb
> +class Event::TangopolixEvents
I only use this and the el Recodo lyrics once. The Tangopolix events list wasn't actually so helpful, but the el-recodo I expect to revisit as he is tweaking and improving his database.

2021-03-11 22:21 UTC, jmarsh24 commented on app/models/video/music_recognition.rb
> +      Youtube.fetch(youtube_id)
Youtube scrapes the YouTube page for the song data. This information is not provided by the YouTube api so I have to grab it using YouTube-dl

2021-03-11 22:26 UTC, jmarsh24 commented on app/models/video/music_recognition/acr_cloud.rb
>      @video = Video.find_by(youtube_id: youtube_id)
There should never be a missing video for this because I only call music recognition on videos which are in the database.

2021-03-11 22:26 UTC, jmarsh24 commented on app/models/video/music_recognition/acr_cloud.rb
>      @video = Video.find_by(youtube_id: youtube_id)
but I added the error anyway

2021-03-11 22:32 UTC, jmarsh24 commented on data/tangodb-datasets/Events.csv
> -,Name
fixed :) I'm loading them using yaml now. 👍

2021-03-11 22:33 UTC, jmarsh24 commented on videos_seeds.rb
> +Video.create({"title"=>"Astor Piazzolla - 100th Anniversary | Bandonegro / Dawid Kostka / Agnieszka Stach & Tymoteusz Ley", "youtube_id"=>"aHcLacNV0-s", "leader_id"=>nil, "follower_id"=>nil, "descrip
this is removed and replaced with my yaml seeding files

2021-03-11 22:42 UTC, jmarsh24 commented on .gitignore
> +/db/seeds/*
I had removed it because I knew you wouldn't like what was in it. haha. It's now removed and I'm using yaml to seed my database.

2021-03-11 23:15 UTC, jmarsh24 commented on app/admin/videos.rb
> +  # end
I had problems getting this batch_action to hide videos working in active admin. Not sure why it's not working. It gives this back as an error. Not a big deal anymore since I have hide functionality for users.

<img width="826" alt="image" src="https://user-images.githubusercontent.com/48605824/110867981-01c9bb00-82c8-11eb-8c7d-6c62118e4df4.png">

2021-03-11 23:17 UTC, jmarsh24 commented on app/admin/videos.rb
> +  # filter :created_at, as: :date_range
fixed. I was caught in between some things while trying to trouble shoot some scope stuff

2021-03-11 23:42 UTC, jmarsh24 commented on app/models/concerns/displayable.rb
> +module Displayable
Do I need to initialize anything else to get the table relations to work?

<img width="824" alt="image" src="https://user-images.githubusercontent.com/48605824/110869942-c6c98680-82cb-11eb-9f0f-8996dc76318d.png">

2021-03-12 05:34 UTC, thomasstephane requested changes

2021-03-12 05:34 UTC, thomasstephane commented on app/models/channel.rb
> +  include Reviewable
it's good practice to organize your rails model the same way and to keep that at the very top. See this for the rest: https://rails.rubystyle.guide/#macro-style-methods

2021-03-12 05:34 UTC, thomasstephane commented on app/models/playlist.rb
> +  scope :not_imported, ->   { where(imported: false) }
Looks like this too could be a concern? importable?

2021-03-12 05:34 UTC, thomasstephane commented on app/models/video/music_recognition/acr_cloud.rb
> +      rescue StandardError => e
indent the rescue to the left. Did you run rubocop on this?

2021-03-12 05:34 UTC, thomasstephane commented on app/models/video/music_recognition/acr_cloud/audio.rb
> +  def sample_start_time
much better name

2021-03-12 05:34 UTC, thomasstephane commented on app/controllers/turbo_controller.rb
> +class TurboController < ApplicationController
I have devise & turbo on 2 apps and it works no problem

2021-03-12 05:36 UTC, thomasstephane commented on app/models/concerns/displayable.rb
> +module Displayable
that's because no you need to explain where song comes from, so:

```ruby
def el_recodo_attributes
  return if @video.song.blank?

  [@video.song.title, @video.song.artist, @video.song.genre].compact.map(&:titleize).join(" - ")
end
```

And so on for the things that are coming from @video

2021-03-12 08:36 UTC, jmarsh24 commented on app/controllers/turbo_controller.rb
> +class TurboController < ApplicationController
What do you think he is highlighting here then? 🤔 Before I incorporated this, I would click on something and the form wouldn't redirect...

2021-03-12 08:52 UTC, jmarsh24 commented on app/models/concerns/displayable.rb
> +module Displayable
thanks for clearing it up. :) fixed.

2021-03-12 08:52 UTC, jmarsh24 commented on app/models/concerns/displayable.rb
> +module Displayable
I converted everything back to string interpolation

2021-03-12 08:59 UTC, jmarsh24 commented on app/models/channel.rb
> +  include Reviewable
Thanks for the link. It's really helpful for me to have these references.

2021-03-12 09:04 UTC, jmarsh24 commented
<img width="294" alt="Screen Shot 2021-03-12 at 10 03 38 AM" src="https://user-images.githubusercontent.com/48605824/110917512-4716d880-831a-11eb-8909-3107fd7a5536.png">

The height on this is the same 34px, but if I'm zoomed out it looks like it's 1 px off. if I zoom in then it's even.

2021-03-12 17:23 UTC, merged