Creating Rspec tests for app
jmarsh24/tangodb pull request #8
Opened 2021-03-15 16:52 UTC by jmarsh24

This branch is dedicated to creating all the app tests

2021-03-22 22:56 UTC, thomasstephane requested changes

2021-03-22 22:56 UTC, thomasstephane commented on spec/models/video_spec.rb
> +      expect(video.display.any_song_attributes).to eq("No Vendrá - Angel D'Agostino - Tango")
Don't test the video test the display, so your tests in the display space should be like that:

```ruby
# in spec/models/video/display_spec.rb
Rspec.describe Video::Display do
  describe "#any_song_attributes" do
    context "when only the song exists" do
      it "returns the song name" do
        song = build(:song, title: "No Vendrá", artist: "Angel D'AGOSTINO", genre: "TANGO")
        video = build(:video, song: song)
        display = described_class.new(video)
        expect(display.any_song_attributes).to eq "No Vendrá - Angel D'Agostino - Tango"
      end
    end
  end
end
```

2021-03-22 22:56 UTC, thomasstephane commented on spec/models/video_spec.rb
> +  end
Same for all these display things

2021-03-22 22:56 UTC, thomasstephane commented on spec/models/video_spec.rb
> +  end
All these scopes should be under a `describe "scope" do` block to be easier to keep together, also same comment as before, you aren't testing anything much here :)

2021-03-22 22:56 UTC, thomasstephane commented on spec/models/video_spec.rb
> +  describe ".paginate" do
remove this if you don't test it

2021-03-22 22:56 UTC, thomasstephane commented on spec/models/video_spec.rb
> +      expect(@result).to include(video)
same here, useless test, ensure that things that shouldn't be included aren't

2021-03-22 22:56 UTC, thomasstephane commented on spec/models/video_spec.rb
> +  end
And same for everything else here

2021-03-22 22:56 UTC, thomasstephane commented on spec/models/videos_search_spec.rb
> +      expect(VideosSearch.count).to eq(1)
what is this testing? Maybe you want to test that the refresh change the count? if so:

```ruby
describe ".refresh" do
  it "includes new video when refreshed" do
    create(:video)
    expect { described_class.refresh }.to change(described_class, :count).from(0).to(1)
  end
end
```

2021-03-22 22:56 UTC, thomasstephane commented on spec/models/videos_search_spec.rb
> +      expect(VideosSearch.count).to include(1)
this is not testing search, this is a copy paste from above

2021-03-22 22:56 UTC, thomasstephane commented on spec/models/channel_spec.rb
> +  let(:channel) { build(:channel) }
no.

2021-03-22 22:56 UTC, thomasstephane commented on spec/models/channel_spec.rb
> +      expect(channel.reload.imported).to eq(true)
none of these tests is testing the `update_videos_count` unless I'm missing something

2021-03-22 22:56 UTC, thomasstephane commented on spec/models/song_spec.rb
> +      expect(song.reload.popularity).to eq(100)
this normalizes right? you should have more than one song then

2021-03-22 22:56 UTC, thomasstephane commented on spec/factories/channels.rb
> +    channel_id { Faker::String.random(length: 12) }
Use a sequence here. https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#sequences

2021-03-22 22:56 UTC, thomasstephane commented on app/models/song.rb
> +      update_all("popularity = CAST(videos_count AS FLOAT) / #{max_times_song_appears} * 100.0")
NEVER use update_all. It bypasses validations. This is a horrible method you should never ever use. Iterate over the values instead, yes it's slower, that's ok.

2021-03-22 22:56 UTC, thomasstephane commented on app/models/song.rb
> +      @max_times_song_appears ||= Song.maximum(:videos_count).to_f
the `to_f` is unnecessary

2021-03-22 22:56 UTC, thomasstephane commented on app/models/channel.rb
> +    def imported?
the method name is misleading, method with `?` should be just testing if something is true or false, not updating it.

2021-03-22 22:56 UTC, thomasstephane commented on app/models/channel.rb
> +      where("videos_count < total_videos_count").update_all(imported: false)
update_all bypass validations. DO not use it.

2021-03-22 22:56 UTC, thomasstephane commented on app/models/channel.rb
> +  scope :imported, -> { where("`channels`.`videos_count` >= `channels`.`total_videos_count`") }
you don't need the ` everywhere here.

```where("channels.videos_count >= channels.total_videos_count")``` should work

2021-03-22 22:56 UTC, thomasstephane commented on app/models/channel.rb
> +  before_save :update_imported, if: -> { total_videos_count_changed? || videos_count_changed? }
what about a method for your if that check both of these? Avoid inline blocks for before saves it makes it hard to read 

```ruby
before_save :update_imported, if: :count_changed?
```

2021-03-23 11:56 UTC, jmarsh24 commented on spec/models/song_spec.rb
> +      expect(@result).to include(song)
Do you mean I should create a separate song with a title that doesn't match and make sure that it doesn't return that song?

`    it "find song by title" do
      song = create(:song, title: "No Vendrá")
      song2 = create(:song, title: "Not matching song")
      result = described_class.title_match("no vendra")
      expect(result).to include(song)
      expect(result).not_to include(song2)
    end`
    
    Something like this?

2021-03-23 21:20 UTC, jmarsh24 commented on spec/models/videos_search_spec.rb
> +      expect(VideosSearch.count).to eq(1)
Do you have any idea why this is happening?

<img width="757" alt="image" src="https://user-images.githubusercontent.com/48605824/112219887-e9da2b80-8c25-11eb-8f4c-ae723de925a0.png">

2021-03-23 21:23 UTC, jmarsh24 commented on spec/models/channel_spec.rb
> +      expect(channel.reload.imported).to eq(true)
Channel has a before save action so upon reload the channel imported_value should be change to the correct imported state based upon the total_video_count and videos_count

2021-03-23 21:23 UTC, jmarsh24 commented on spec/models/channel_spec.rb
> +      expect(channel.reload.imported).to eq(true)
I'm not sure if it's the correct way to test it though. 🤔 but it's simple and seems to work.

2021-03-23 23:17 UTC, jmarsh24 commented on spec/models/video_spec.rb
> +  end
Is it ok to use describe twice? or should I use context scope, describe scope....?

2021-03-25 20:19 UTC, thomasstephane requested changes

2021-03-25 20:19 UTC, thomasstephane commented on spec/models/video_spec.rb
> +  end
run rubicon on this file (and all the others....) plenty to correct here :)

2021-03-25 20:19 UTC, thomasstephane commented on spec/support/models/shared_examples/importable.rb
> +      expect(described_class.imported).not_to include(not_imported)
same as before, check an equality instead

2021-03-26 20:57 UTC, jmarsh24 commented on app/models/playlist.rb
> -  include Reviewable
if the title is less than 2 strings long, then there will be a lot of false positives.

2021-03-26 20:58 UTC, jmarsh24 commented on app/models/event.rb
> +    return if search_title.split.size < 2 || videos_with_event_title_match.empty?
if the title is less than 2 strings long, then there will be a lot of false positives.

2021-03-26 21:06 UTC, jmarsh24 commented on app/models/playlist.rb
> -  include Reviewable
I didn't have a column in the database for it.

2021-03-26 21:07 UTC, jmarsh24 commented on app/models/song.rb
> +    "#{title.titleize} - #{artist.split("'").map(&:titleize).join("'")} - #{genre.titleize}"
Titlize doesn't title a name like "D'Agostino" properly it would produce "D'agostino" instead.

2021-03-27 17:47 UTC, thomasstephane approved these changes

2021-03-27 17:47 UTC, merged